//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radischevo.Wahha.Web.Routing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Radischevo.Wahha.Web.Routing.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A path segment that contains more than one section, such as a literal section or a parameter, cannot contain a catch-all parameter..
        /// </summary>
        internal static string Error_CatchAllInMultiSegment {
            get {
                return ResourceManager.GetString("Error_CatchAllInMultiSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A catch-all parameter can only appear as the last segment of the route URL..
        /// </summary>
        internal static string Error_CatchAllMustBeLast {
            get {
                return ResourceManager.GetString("Error_CatchAllMustBeLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A path segment cannot contain two consecutive parameters. They must be separated by a &apos;/&apos; or by a literal string..
        /// </summary>
        internal static string Error_ConsecutiveRouteParameters {
            get {
                return ResourceManager.GetString("Error_ConsecutiveRouteParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route URL separator character &apos;/&apos; cannot appear consecutively. It must be separated by either a parameter or a literal value..
        /// </summary>
        internal static string Error_ConsecutiveSeparators {
            get {
                return ResourceManager.GetString("Error_ConsecutiveSeparators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint type cannot be an empty string..
        /// </summary>
        internal static string Error_ConstraintTypeCannotBeEmpty {
            get {
                return ResourceManager.GetString("Error_ConstraintTypeCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must have a public parameterless constructor to be instantiated using the default factory..
        /// </summary>
        internal static string Error_CouldNotInstantiateHttpHandler {
            get {
                return ResourceManager.GetString("Error_CouldNotInstantiateHttpHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route parameter name &apos;{0}&apos; appears more than once in the URL..
        /// </summary>
        internal static string Error_DuplicateRouteParameterName {
            get {
                return ResourceManager.GetString("Error_DuplicateRouteParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route table provider type &apos;{0}&apos; must implement the &apos;{1}&apos; interface..
        /// </summary>
        internal static string Error_IncompatibleRouteTableProvider {
            get {
                return ResourceManager.GetString("Error_IncompatibleRouteTableProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is incomplete escape sequence found in this path segment: &apos;{0}&apos;. Please check the route syntax..
        /// </summary>
        internal static string Error_IncompleteEscapeSequenceInRoute {
            get {
                return ResourceManager.GetString("Error_IncompleteEscapeSequenceInRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route handler type &apos;{0}&apos; must implement the &apos;{1}&apos; interface..
        /// </summary>
        internal static string Error_InvalidRouteHandlerType {
            get {
                return ResourceManager.GetString("Error_InvalidRouteHandlerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route parameter name &apos;{0}&apos; is invalid. Route parameter names must be non-empty and cannot contain these characters: &apos;{{&apos;, &apos;}}&apos;, &apos;[&apos;, &apos;]&apos;, &apos;/&apos;, &apos;?&apos;.
        /// </summary>
        internal static string Error_InvalidRouteParameterName {
            get {
                return ResourceManager.GetString("Error_InvalidRouteParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route variable name &apos;{0}&apos; is invalid. Route variable names must be non-empty and cannot contain these characters: &apos;{{&apos;, &apos;}}&apos;, &apos;[&apos;, &apos;]&apos;, &apos;/&apos;, &apos;?&apos;.
        /// </summary>
        internal static string Error_InvalidRouteVariableName {
            get {
                return ResourceManager.GetString("Error_InvalidRouteVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A route that matches the requested values could not be located in the route table..
        /// </summary>
        internal static string Error_MatchingRouteCouldNotBeLocated {
            get {
                return ResourceManager.GetString("Error_MatchingRouteCouldNotBeLocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route handler &apos;{0}&apos; did not return an IHttpHandler from its GetHttpHandler() method..
        /// </summary>
        internal static string Error_NoHttpHandlerFound {
            get {
                return ResourceManager.GetString("Error_NoHttpHandlerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A RouteHandler must be specified for the selected route..
        /// </summary>
        internal static string Error_NoRouteHandlerFound {
            get {
                return ResourceManager.GetString("Error_NoRouteHandlerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The incoming request does not match any route..
        /// </summary>
        internal static string Error_NoRouteMatched {
            get {
                return ResourceManager.GetString("Error_NoRouteMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route table provider is not initialized. Please check the configuration file..
        /// </summary>
        internal static string Error_PersistenceProviderNotInitialized {
            get {
                return ResourceManager.GetString("Error_PersistenceProviderNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RouteData must contain an item named &apos;{0}&apos; with a non-empty string value..
        /// </summary>
        internal static string Error_RequiredValueNotFound {
            get {
                return ResourceManager.GetString("Error_RequiredValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A RoutableUserControl can only be used inside pages that derive from RoutablePage..
        /// </summary>
        internal static string Error_RoutableControlRequiresRoutablePage {
            get {
                return ResourceManager.GetString("Error_RoutableControlRequiresRoutablePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route variable &apos;{0}&apos; must be defined before the route can be used..
        /// </summary>
        internal static string Error_UndefinedRouteVariable {
            get {
                return ResourceManager.GetString("Error_UndefinedRouteVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected symbol &apos;{0}&apos; found in this path segment: &apos;{1}&apos;. Please check the route syntax..
        /// </summary>
        internal static string Error_UnexpectedSymbolInRoute {
            get {
                return ResourceManager.GetString("Error_UnexpectedSymbolInRoute", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to Could not parse the configuration file. See the inner exception for details..
        /// </summary>
        internal static string Error_UnableToLoadConfiguration {
            get {
                return ResourceManager.GetString("Error_UnableToLoadConfiguration", resourceCulture);
            }
        }
    }
}
