using System;
using System.Collections.Generic;

using Radischevo.Wahha.Core;
using Radischevo.Wahha.Data.Mapping;

namespace ConsoleTester
{
	[Serializable]
	[Table(Name = "Wahha.Topics", Schema = "dbo")]
	public class Topic
	{
		#region Instance Fields
		[Column(Name = "id", IsKey = true, AutoGenerated = true)]
		private long _id;
		
		private string _title;
		[Column(Name = "dateCreated", Binder = typeof(TimestampDbColumnBinder))]
		private DateTime _dateCreated;
		[Column(Name = "content", Binder = typeof(ReverseStringColumnBinder))]
		private Link<string> _content;
		
		[Association(ThisKey = "id", OtherKey = "topic", Prefix = "comments.")]
		private EnumerableLink<Comment> _comments;
		#endregion
		
		#region Constructors
		public Topic ()
		{
			_comments = new EnumerableLink<Comment>();
		}
		#endregion
		
		#region Instance Properties
		public long Id
		{
			get
			{
				return _id;
			}
		}
		
		public DateTime DateCreated
		{
			get
			{
				return _dateCreated;
			}
		}
		
		[Column(Name = "title")]
		public string Title
		{
			get
			{
				return _title;
			}
			set
			{
				_title = value;
			}
		}
		
		public string Content
		{
			get
			{
				return _content.Value;
			}
			set
			{
				_content.Value = value;
			}
		}
		
		public IEnumerable<Comment> Comments
		{
			get
			{
				return _comments;
			}
		}
		#endregion
	}
}

