//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radischevo.Wahha.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Radischevo.Wahha.Core.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert the &apos;{0}&apos; argument to the specified type &apos;{1}&apos;..
        /// </summary>
        internal static string Error_CouldNotConvertType {
            get {
                return ResourceManager.GetString("Error_CouldNotConvertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a dynamic accessor for property &apos;{0}&apos; of type &apos;{1}&apos;.
        /// </summary>
        internal static string Error_CouldNotCreateAccessorForIndexer {
            get {
                return ResourceManager.GetString("Error_CouldNotCreateAccessorForIndexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a dynamic converter for the specified object of type &apos;{0}&apos;..
        /// </summary>
        internal static string Error_CouldNotCreateDynamicConverter {
            get {
                return ResourceManager.GetString("Error_CouldNotCreateDynamicConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a TryGetValue delegate fot the &apos;{0}&apos; type..
        /// </summary>
        internal static string Error_CouldNotCreateTryGetValueDelegateForType {
            get {
                return ResourceManager.GetString("Error_CouldNotCreateTryGetValueDelegateForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the base-16 encoded string must be an odd number..
        /// </summary>
        internal static string Error_EncodedStringLengthMustBeOdd {
            get {
                return ResourceManager.GetString("Error_EncodedStringLengthMustBeOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified binding expression is invalid..
        /// </summary>
        internal static string Error_InvalidBindingExpressionFormat {
            get {
                return ResourceManager.GetString("Error_InvalidBindingExpressionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified indexer expression is invalid..
        /// </summary>
        internal static string Error_InvalidIndexerExpressionFormat {
            get {
                return ResourceManager.GetString("Error_InvalidIndexerExpressionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load a linked object since its source is not initialized..
        /// </summary>
        internal static string Error_LinkSourceIsNotInitialized {
            get {
                return ResourceManager.GetString("Error_LinkSourceIsNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member binding expression cannot be empty..
        /// </summary>
        internal static string Error_MemberBindingExpressionIsEmpty {
            get {
                return ResourceManager.GetString("Error_MemberBindingExpressionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not perform the argument check for the specified method &apos;{0}&apos; of type &apos;{1}&apos;. Type arguments for the method must be set before checking..
        /// </summary>
        internal static string Error_MethodCouldNotBeGenericDefinition {
            get {
                return ResourceManager.GetString("Error_MethodCouldNotBeGenericDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default indexer could not be found at the type &apos;{0}&apos;..
        /// </summary>
        internal static string Error_MissingIndexer {
            get {
                return ResourceManager.GetString("Error_MissingIndexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field or property with the name &apos;{1}&apos; could not be found at the type &apos;{0}&apos;..
        /// </summary>
        internal static string Error_MissingMember {
            get {
                return ResourceManager.GetString("Error_MissingMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The offset in the array should be less than its length..
        /// </summary>
        internal static string Error_OffsetMustBeLessThanArrayLength {
            get {
                return ResourceManager.GetString("Error_OffsetMustBeLessThanArrayLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation has timed out after {0}..
        /// </summary>
        internal static string Error_OperationTimeout {
            get {
                return ResourceManager.GetString("Error_OperationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the &apos;{0}&apos; parameter should be greater than {1}..
        /// </summary>
        internal static string Error_ParameterMustBeGreaterThan {
            get {
                return ResourceManager.GetString("Error_ParameterMustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the &apos;{0}&apos; parameter should be greater than or equal to {1}..
        /// </summary>
        internal static string Error_ParameterMustBeGreaterThanOrEqual {
            get {
                return ResourceManager.GetString("Error_ParameterMustBeGreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to assign value to readonly property &apos;{0}&apos; of type &apos;{1}&apos;..
        /// </summary>
        internal static string Error_PropertyIsReadOnly {
            get {
                return ResourceManager.GetString("Error_PropertyIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get the value of the property &apos;{0}&apos; of type &apos;{1}&apos;..
        /// </summary>
        internal static string Error_PropertyIsWriteOnly {
            get {
                return ResourceManager.GetString("Error_PropertyIsWriteOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert the &apos;{0}&apos; argument to the specified type. Type&apos;{1}&apos; does not allow null values..
        /// </summary>
        internal static string Error_TargetTypeIsNotNullable {
            get {
                return ResourceManager.GetString("Error_TargetTypeIsNotNullable", resourceCulture);
            }
        }
    }
}
