//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radischevo.Wahha.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Radischevo.Wahha.Data.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous column name &apos;{0}&apos; found in the data record..
        /// </summary>
        internal static string Error_AmbiguousColumnName {
            get {
                return ResourceManager.GetString("Error_AmbiguousColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string Error_ArrayTypeIsNotSupported {
            get {
                return ResourceManager.GetString("Error_ArrayTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currently configured cache provider &apos;{0}&apos; does not support item tagging..
        /// </summary>
        internal static string Error_CacheProviderDoesNotSupportTags {
            get {
                return ResourceManager.GetString("Error_CacheProviderDoesNotSupportTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot enumerate the result set more than once..
        /// </summary>
        internal static string Error_CannotEnumerateMoreThanOnce {
            get {
                return ResourceManager.GetString("Error_CannotEnumerateMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular reference found at type &apos;{0}&apos;..
        /// </summary>
        internal static string Error_CircularReferenceFoundAtType {
            get {
                return ResourceManager.GetString("Error_CircularReferenceFoundAtType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a field with the specified name &apos;{0}&apos; in the result set..
        /// </summary>
        internal static string Error_ColumnNameDoesNotExistInResultSet {
            get {
                return ResourceManager.GetString("Error_ColumnNameDoesNotExistInResultSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a field with the specified ordinal &apos;{0}&apos; in the result set..
        /// </summary>
        internal static string Error_ColumnOrdinalDoesNotExistInResultSet {
            get {
                return ResourceManager.GetString("Error_ColumnOrdinalDoesNotExistInResultSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database query command must be initialized to complete the operation..
        /// </summary>
        internal static string Error_CommandIsNotInitialized {
            get {
                return ResourceManager.GetString("Error_CommandIsNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma symbol was expected in the array declaration..
        /// </summary>
        internal static string Error_CommaWasExpectedInArrayDeclaration {
            get {
                return ResourceManager.GetString("Error_CommaWasExpectedInArrayDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any connection strings in the configuration file..
        /// </summary>
        internal static string Error_ConnectionStringNotConfigured {
            get {
                return ResourceManager.GetString("Error_ConnectionStringNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string cannot be null or an empty string..
        /// </summary>
        internal static string Error_ConnectionStringNotInitialized {
            get {
                return ResourceManager.GetString("Error_ConnectionStringNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert the object to the specified type &apos;{0}&apos;..
        /// </summary>
        internal static string Error_CouldNotConvertObjectToType {
            get {
                return ResourceManager.GetString("Error_CouldNotConvertObjectToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the necessary list type &apos;{0}&apos;..
        /// </summary>
        internal static string Error_CouldNotCreateListType {
            get {
                return ResourceManager.GetString("Error_CouldNotCreateListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided link can not be materialized since it can not be explicitly converted to the &apos;Link&lt;TAssociation&gt;&apos; type..
        /// </summary>
        internal static string Error_CouldNotMaterializeCollectionLink {
            get {
                return ResourceManager.GetString("Error_CouldNotMaterializeCollectionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve type &apos;{0}&apos;..
        /// </summary>
        internal static string Error_CouldNotResolveType {
            get {
                return ResourceManager.GetString("Error_CouldNotResolveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change transaction isolation level since the Execute method was already called..
        /// </summary>
        internal static string Error_CouldNotSetIsolationLevelAfterInitialize {
            get {
                return ResourceManager.GetString("Error_CouldNotSetIsolationLevelAfterInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth limit exceeded..
        /// </summary>
        internal static string Error_DepthLimitExceeded {
            get {
                return ResourceManager.GetString("Error_DepthLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserializer type mismatch..
        /// </summary>
        internal static string Error_DeserializerTypeMismatch {
            get {
                return ResourceManager.GetString("Error_DeserializerTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided expression &apos;{0}&apos; must be a constructor call..
        /// </summary>
        internal static string Error_ExpressionMustBeAConstructorCall {
            get {
                return ResourceManager.GetString("Error_ExpressionMustBeAConstructorCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra comma at array ending found..
        /// </summary>
        internal static string Error_ExtraCommaAtArrayEndingFound {
            get {
                return ResourceManager.GetString("Error_ExtraCommaAtArrayEndingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index (zero based) must be greater than or equal to zero and less than the size of the argument list..
        /// </summary>
        internal static string Error_FormatParameterMismatch {
            get {
                return ResourceManager.GetString("Error_FormatParameterMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid array starting symbol..
        /// </summary>
        internal static string Error_IllegalArrayStartingSymbol {
            get {
                return ResourceManager.GetString("Error_IllegalArrayStartingSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal JavaScript primitive..
        /// </summary>
        internal static string Error_IllegalJavaScriptPrimitive {
            get {
                return ResourceManager.GetString("Error_IllegalJavaScriptPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; must implement the ICacheProvider or ITaggedCacheProvider interface and have a public parameterless constructor..
        /// </summary>
        internal static string Error_IncompatibleCacheProviderType {
            get {
                return ResourceManager.GetString("Error_IncompatibleCacheProviderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; must implement the IDbMaterializer interface..
        /// </summary>
        internal static string Error_IncompatibleMaterializerType {
            get {
                return ResourceManager.GetString("Error_IncompatibleMaterializerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; must implement the IDbDataProviderFactory interface and have a public parameterless constructor..
        /// </summary>
        internal static string Error_IncompatibleProviderFactoryType {
            get {
                return ResourceManager.GetString("Error_IncompatibleProviderFactoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid array ending symbol..
        /// </summary>
        internal static string Error_InvalidArrayEndingSymbol {
            get {
                return ResourceManager.GetString("Error_InvalidArrayEndingSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided expression constructs objects of &apos;{0}&apos; type, but the type compatible with &apos;{1}&apos; is required..
        /// </summary>
        internal static string Error_InvalidConstructorExpressionType {
            get {
                return ResourceManager.GetString("Error_InvalidConstructorExpressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid enum type &apos;{0}&apos;..
        /// </summary>
        internal static string Error_InvalidEnumType {
            get {
                return ResourceManager.GetString("Error_InvalidEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid escape sequence..
        /// </summary>
        internal static string Error_InvalidEscapeSequence {
            get {
                return ResourceManager.GetString("Error_InvalidEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid member name..
        /// </summary>
        internal static string Error_InvalidMemberName {
            get {
                return ResourceManager.GetString("Error_InvalidMemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided method returns a value of &apos;{0}&apos; type, but the &apos;{1}&apos; type is required..
        /// </summary>
        internal static string Error_InvalidMethodReturnType {
            get {
                return ResourceManager.GetString("Error_InvalidMethodReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid object definition..
        /// </summary>
        internal static string Error_InvalidObjectDefinition {
            get {
                return ResourceManager.GetString("Error_InvalidObjectDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum JSON string length exceeded..
        /// </summary>
        internal static string Error_MaximumJsonStringLengthExceeded {
            get {
                return ResourceManager.GetString("Error_MaximumJsonStringLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum recursion depth exceeded..
        /// </summary>
        internal static string Error_MaximumRecursionDepthExceeded {
            get {
                return ResourceManager.GetString("Error_MaximumRecursionDepthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression parameter &apos;{0}&apos; must target the lambda argument..
        /// </summary>
        internal static string Error_MethodCallMustTargetLambdaArgument {
            get {
                return ResourceManager.GetString("Error_MethodCallMustTargetLambdaArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access the &apos;{0}&apos;. The object is disposed..
        /// </summary>
        internal static string Error_ObjectDisposed {
            get {
                return ResourceManager.GetString("Error_ObjectDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening brace expected..
        /// </summary>
        internal static string Error_OpeningBraceExpected {
            get {
                return ResourceManager.GetString("Error_OpeningBraceExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the &apos;{0}&apos; parameter should be greater than {1}..
        /// </summary>
        internal static string Error_ParameterMustBeGreaterThan {
            get {
                return ResourceManager.GetString("Error_ParameterMustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the &apos;{0}&apos; parameter should be greater than or equal to {1}..
        /// </summary>
        internal static string Error_ParameterMustBeGreaterThanOrEqual {
            get {
                return ResourceManager.GetString("Error_ParameterMustBeGreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read the result set from the closed data reader..
        /// </summary>
        internal static string Error_ReaderIsEmpty {
            get {
                return ResourceManager.GetString("Error_ReaderIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector expression &apos;{0}&apos; must be a method call..
        /// </summary>
        internal static string Error_SelectorMustBeAMethodCall {
            get {
                return ResourceManager.GetString("Error_SelectorMustBeAMethodCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String is not quoted..
        /// </summary>
        internal static string Error_StringIsNotQuoted {
            get {
                return ResourceManager.GetString("Error_StringIsNotQuoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied dictionary type is not supported..
        /// </summary>
        internal static string Error_SuppliedDictionaryTypeIsNotSupported {
            get {
                return ResourceManager.GetString("Error_SuppliedDictionaryTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must have a parameterless constructor..
        /// </summary>
        internal static string Error_TypeMustHaveParameterlessConstructor {
            get {
                return ResourceManager.GetString("Error_TypeMustHaveParameterlessConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data provider could not connect to the specified data source..
        /// </summary>
        internal static string Error_UnableToConnect {
            get {
                return ResourceManager.GetString("Error_UnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse the configuration file. See the inner exception for details..
        /// </summary>
        internal static string Error_UnableToLoadConfiguration {
            get {
                return ResourceManager.GetString("Error_UnableToLoadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database command type &apos;{0}&apos; is not supported by the provider..
        /// </summary>
        internal static string Error_UnsupportedCommandType {
            get {
                return ResourceManager.GetString("Error_UnsupportedCommandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated string constant..
        /// </summary>
        internal static string Error_UnterminatedStringConstant {
            get {
                return ResourceManager.GetString("Error_UnterminatedStringConstant", resourceCulture);
            }
        }
    }
}
