using System;
using System.Reflection;

using Radischevo.Wahha.Core;

namespace Radischevo.Wahha.Data.Mapping
{
	public class AttributedMetaColumn : MetaColumn
	{
		#region Instance Fields
		private readonly string _name;
		private readonly bool _autoGenerated;
		private readonly bool _autoUpdate;
		private readonly bool _isKey;
		private readonly bool _isNullable;
		private readonly Type _binderType;
		private IDbColumnBinder _binder;
		#endregion
		
		#region Constructors
		public AttributedMetaColumn (MetaType declaringType, 
			MemberInfo member, ColumnAttribute attribute)
			: base(declaringType, member)
		{
			Precondition.Require(attribute, () => Error.ArgumentNull("attribute"));
			
			_name = attribute.Name ?? member.Name;
			_autoGenerated = attribute.AutoGenerated;
			_autoUpdate = attribute.AutoUpdate;
			_isKey = attribute.IsKey;
			_isNullable = attribute.Nullable;
			_binderType = attribute.Binder;
		}
		#endregion
		
		#region Instance Properties
		public override string Name 
		{
			get 
			{
				return _name;
			}
		}
		
		public override bool AutoGenerated 
		{
			get 
			{
				return _autoGenerated;
			}
		}

		public override bool AutoUpdate 
		{
			get 
			{
				return _autoUpdate;
			}
		}

		public override bool IsKey 
		{
			get 
			{
				return _isKey;
			}
		}
		
		public override bool IsNullable 
		{
			get 
			{
				return _isNullable;
			}
		}
		
		public override IDbColumnBinder Binder 
		{
			get 
			{
				if (_binder == null)
					_binder = CreateBinder(_binderType);
				
				return _binder;
			}
		}
		#endregion
	}
}

