using System;

namespace Radischevo.Wahha.Data.Mapping
{
	/// <summary>
    /// Use this attribute to identify the properties of the entity objects that map 
    /// to table columns. If no specific name is supplied, then the column and property names must be identical. 
    /// This attribute can also be used to override constraints.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false, Inherited = true)]
    public sealed class ColumnAttribute : Attribute
	{
		#region Instance Fields
        private string _name;
		private bool _isKey;
        private bool _nullable;
        private bool _autoUpdate;
        private bool _autoGenerated;
		private Type _binder;
        #endregion

        #region Constructors
        /// <summary>
        /// Initializes a new instance of the 
        /// <see cref="Radischevo.Wahha.Data.Mapping.ColumnAttribute"/> class.
        /// </summary>
        public ColumnAttribute()
        {
            _nullable = true;            
        }
        #endregion

        #region Instance Properties
        /// <summary>
        /// Gets the name of the database column 
        /// for storing the property decorated with this attribute.
        /// </summary>
        public string Name
        {
            get 
            { 
                return _name; 
            }
            set
            {
                _name = value;
            }
        }

        /// <summary>
        /// Gets or sets the value, indicating whether <c>null</c> values are
        /// allowed in the database.
        /// </summary>
        public bool Nullable
        {
            get 
            { 
                return _nullable; 
            }
            set 
            { 
                _nullable = value; 
            }
        }

        /// <summary>
        /// Gets or sets the value indicating that the column must be read after each insert and update. 
        /// </summary>
        /// <remarks>
        /// Setting AutoUpdate to true is primarily useful for columns 
        /// that are set internally by the database. Using this feature will significantly impact 
        /// performance for the worse, as for every update/insert another select will be performed.
        /// </remarks>
        public bool AutoUpdate
        {
            get 
            { 
                return _autoUpdate; 
            }
            set 
            { 
                _autoUpdate = value; 
            }
        }

        /// <summary>
        /// Gets or sets the value, indicating whether the 
        /// property or field is mapped to the primary key column.
        /// </summary>
        public bool IsKey
        {
            get
            {
                return _isKey;
            }
            set
            {
                _isKey = value;
            }
        }

        /// <summary>
        /// Gets or sets the value, indicating whether this 
        /// column value is automatically assigned 
        /// by the database on insert. 
        /// </summary>
        public bool AutoGenerated
        {
            get
            {
                return _autoGenerated;
            }
            set
            {
                _autoGenerated = value;
            }
        }

		/// <summary>
		/// Gets or sets the type of the <see cref="Radischevo.Wahha.Data.Mapping.IColumnBinder"/> 
		/// which is used to convert between database column and property values.
		/// </summary>
		public Type Binder
		{
			get
			{
				return _binder;
			}
			set
			{
				_binder = value;
			}
		}
        #endregion
	}
}

