//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Radischevo.Wahha.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Radischevo.Wahha.Web.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string Error_ArrayTypeIsNotSupported {
            get {
                return ResourceManager.GetString("Error_ArrayTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTLIST references undefined ELEMENT {0}..
        /// </summary>
        internal static string Error_AttributeListReferencesToAnUndefinedElement {
            get {
                return ResourceManager.GetString("Error_AttributeListReferencesToAnUndefinedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular reference found at type &apos;{0}&apos;..
        /// </summary>
        internal static string Error_CircularReferenceFoundAtType {
            get {
                return ResourceManager.GetString("Error_CircularReferenceFoundAtType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma symbol was expected in the array declaration..
        /// </summary>
        internal static string Error_CommaWasExpectedInArrayDeclaration {
            get {
                return ResourceManager.GetString("Error_CommaWasExpectedInArrayDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Model was not closed..
        /// </summary>
        internal static string Error_ContentModelWasNotClosed {
            get {
                return ResourceManager.GetString("Error_ContentModelWasNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert the object to the specified type &apos;{0}&apos;..
        /// </summary>
        internal static string Error_CouldNotConvertObjectToType {
            get {
                return ResourceManager.GetString("Error_CouldNotConvertObjectToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the necessary list type &apos;{0}&apos;..
        /// </summary>
        internal static string Error_CouldNotCreateListType {
            get {
                return ResourceManager.GetString("Error_CouldNotCreateListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting &apos;[&apos; but found {0}..
        /// </summary>
        internal static string Error_CouldNotParseConditionalSection {
            get {
                return ResourceManager.GetString("Error_CouldNotParseConditionalSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premature {0} parsing entity reference..
        /// </summary>
        internal static string Error_CouldNotParseEntityReference {
            get {
                return ResourceManager.GetString("Error_CouldNotParseEntityReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse the nested template referenced through the include directive..
        /// </summary>
        internal static string Error_CouldNotParseNestedTemplate {
            get {
                return ResourceManager.GetString("Error_CouldNotParseNestedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve type &apos;{0}&apos;..
        /// </summary>
        internal static string Error_CouldNotResolveType {
            get {
                return ResourceManager.GetString("Error_CouldNotResolveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth limit exceeded..
        /// </summary>
        internal static string Error_DepthLimitExceeded {
            get {
                return ResourceManager.GetString("Error_DepthLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserializer type mismatch..
        /// </summary>
        internal static string Error_DeserializerTypeMismatch {
            get {
                return ResourceManager.GetString("Error_DeserializerTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTD does not match the document type..
        /// </summary>
        internal static string Error_DtdDoesNotMatchDocumentType {
            get {
                return ResourceManager.GetString("Error_DtdDoesNotMatchDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate main directive &apos;{0}&apos; found..
        /// </summary>
        internal static string Error_DuplicateMainDirective {
            get {
                return ResourceManager.GetString("Error_DuplicateMainDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code render expression cannot be empty..
        /// </summary>
        internal static string Error_EmptyCodeRenderExpression {
            get {
                return ResourceManager.GetString("Error_EmptyCodeRenderExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting comment &apos;&lt;!--&apos; but found &apos;{0}&apos;..
        /// </summary>
        internal static string Error_ExpectingComment {
            get {
                return ResourceManager.GetString("Error_ExpectingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting comment delimiter &apos;--&apos; but found {0}..
        /// </summary>
        internal static string Error_ExpectingCommentDelimiter {
            get {
                return ResourceManager.GetString("Error_ExpectingCommentDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found &apos;{0}&apos;, but expecting declaration starting with &apos;&lt;!&apos;..
        /// </summary>
        internal static string Error_ExpectingDeclaration {
            get {
                return ResourceManager.GetString("Error_ExpectingDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting end of ELEMENT declaration &apos;&gt;&apos; but found &apos;{0}&apos;..
        /// </summary>
        internal static string Error_ExpectingEndOfElementDeclaration {
            get {
                return ResourceManager.GetString("Error_ExpectingEndOfElementDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting end of entity declaration &apos;&gt;&apos; but found &apos;{0}&apos;..
        /// </summary>
        internal static string Error_ExpectingEndOfEntityDeclaration {
            get {
                return ResourceManager.GetString("Error_ExpectingEndOfEntityDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting inclusions name group..
        /// </summary>
        internal static string Error_ExpectingInclusionsNameGroup {
            get {
                return ResourceManager.GetString("Error_ExpectingInclusionsNameGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting name group &apos;(&apos;, but found &apos;{0}&apos;..
        /// </summary>
        internal static string Error_ExpectingNameGroup {
            get {
                return ResourceManager.GetString("Error_ExpectingNameGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting public identifier literal but found &apos;{0}&apos;..
        /// </summary>
        internal static string Error_ExpectingPublicIdentifierLiteral {
            get {
                return ResourceManager.GetString("Error_ExpectingPublicIdentifierLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting system identifier literal but found &apos;{0}&apos;..
        /// </summary>
        internal static string Error_ExpectingSystemIdentifierLiteral {
            get {
                return ResourceManager.GetString("Error_ExpectingSystemIdentifierLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra comma at array ending found..
        /// </summary>
        internal static string Error_ExtraCommaAtArrayEndingFound {
            get {
                return ResourceManager.GetString("Error_ExtraCommaAtArrayEndingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid array starting symbol..
        /// </summary>
        internal static string Error_IllegalArrayStartingSymbol {
            get {
                return ResourceManager.GetString("Error_IllegalArrayStartingSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal JavaScript primitive..
        /// </summary>
        internal static string Error_IllegalJavaScriptPrimitive {
            get {
                return ResourceManager.GetString("Error_IllegalJavaScriptPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector &apos;{0}&apos; is inconsistent with {1} group..
        /// </summary>
        internal static string Error_InconsistentConnector {
            get {
                return ResourceManager.GetString("Error_InconsistentConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify input either via Href or InputStream properties..
        /// </summary>
        internal static string Error_InputStreamIsUndefined {
            get {
                return ResourceManager.GetString("Error_InputStreamIsUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid array ending symbol..
        /// </summary>
        internal static string Error_InvalidArrayEndingSymbol {
            get {
                return ResourceManager.GetString("Error_InvalidArrayEndingSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute value &apos;{0}&apos; not supported..
        /// </summary>
        internal static string Error_InvalidAttributeDefinitionPresenceValue {
            get {
                return ResourceManager.GetString("Error_InvalidAttributeDefinitionPresenceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttributeType {0} is not valid for an attribute definition with an enumerated value..
        /// </summary>
        internal static string Error_InvalidAttributeDefinitionType {
            get {
                return ResourceManager.GetString("Error_InvalidAttributeDefinitionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string Error_InvalidAttributeDefinitionTypeValue {
            get {
                return ResourceManager.GetString("Error_InvalidAttributeDefinitionTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character 0x{0} in encoding..
        /// </summary>
        internal static string Error_InvalidCharacterInEncoding {
            get {
                return ResourceManager.GetString("Error_InvalidCharacterInEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid declaration &apos;&lt;!{0}&apos;.  Expecting &apos;ENTITY&apos;, &apos;ELEMENT&apos; or &apos;ATTLIST&apos;..
        /// </summary>
        internal static string Error_InvalidDeclaration {
            get {
                return ResourceManager.GetString("Error_InvalidDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid syntax at &apos;{0}&apos;..
        /// </summary>
        internal static string Error_InvalidDeclarationSyntax {
            get {
                return ResourceManager.GetString("Error_InvalidDeclarationSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declared content type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string Error_InvalidDeclaredContentTypeValue {
            get {
                return ResourceManager.GetString("Error_InvalidDeclaredContentTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid enum type &apos;{0}&apos;..
        /// </summary>
        internal static string Error_InvalidEnumType {
            get {
                return ResourceManager.GetString("Error_InvalidEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid escape sequence..
        /// </summary>
        internal static string Error_InvalidEscapeSequence {
            get {
                return ResourceManager.GetString("Error_InvalidEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid external identifier &apos;{0}&apos;.  Expecing &apos;PUBLIC&apos; or &apos;SYSTEM&apos;..
        /// </summary>
        internal static string Error_InvalidExternalIdentifierLiteral {
            get {
                return ResourceManager.GetString("Error_InvalidExternalIdentifierLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literal content type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string Error_InvalidLiteralTypeValue {
            get {
                return ResourceManager.GetString("Error_InvalidLiteralTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported marked section type &apos;{0}&apos;..
        /// </summary>
        internal static string Error_InvalidMarkedSectionType {
            get {
                return ResourceManager.GetString("Error_InvalidMarkedSectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid member name..
        /// </summary>
        internal static string Error_InvalidMemberName {
            get {
                return ResourceManager.GetString("Error_InvalidMemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name character &apos;{0}&apos;..
        /// </summary>
        internal static string Error_InvalidNameCharacter {
            get {
                return ResourceManager.GetString("Error_InvalidNameCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name start character &apos;{0}&apos;..
        /// </summary>
        internal static string Error_InvalidNameStartCharacter {
            get {
                return ResourceManager.GetString("Error_InvalidNameStartCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid object definition..
        /// </summary>
        internal static string Error_InvalidObjectDefinition {
            get {
                return ResourceManager.GetString("Error_InvalidObjectDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum JSON string length exceeded..
        /// </summary>
        internal static string Error_MaximumJsonStringLengthExceeded {
            get {
                return ResourceManager.GetString("Error_MaximumJsonStringLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum recursion depth exceeded..
        /// </summary>
        internal static string Error_MaximumRecursionDepthExceeded {
            get {
                return ResourceManager.GetString("Error_MaximumRecursionDepthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing token before connector &apos;{0}&apos;..
        /// </summary>
        internal static string Error_MissingTokenBeforeConnector {
            get {
                return ResourceManager.GetString("Error_MissingTokenBeforeConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not on an attribute..
        /// </summary>
        internal static string Error_NotOnAnAttribute {
            get {
                return ResourceManager.GetString("Error_NotOnAnAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not on an entity reference..
        /// </summary>
        internal static string Error_NotOnAnEntityReference {
            get {
                return ResourceManager.GetString("Error_NotOnAnEntityReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening brace expected..
        /// </summary>
        internal static string Error_OpeningBraceExpected {
            get {
                return ResourceManager.GetString("Error_OpeningBraceExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter entity cannot close a paren outside it&apos;s own scope..
        /// </summary>
        internal static string Error_ParameterEntityClosedOutsideTheScope {
            get {
                return ResourceManager.GetString("Error_ParameterEntityClosedOutsideTheScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the &apos;{0}&apos; parameter should be greater than {1}..
        /// </summary>
        internal static string Error_ParameterMustBeGreaterThan {
            get {
                return ResourceManager.GetString("Error_ParameterMustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the &apos;{0}&apos; parameter should be greater than or equal to {1}..
        /// </summary>
        internal static string Error_ParameterMustBeGreaterThanOrEqual {
            get {
                return ResourceManager.GetString("Error_ParameterMustBeGreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String is not quoted..
        /// </summary>
        internal static string Error_StringIsNotQuoted {
            get {
                return ResourceManager.GetString("Error_StringIsNotQuoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied dictionary type is not supported..
        /// </summary>
        internal static string Error_SuppliedDictionaryTypeIsNotSupported {
            get {
                return ResourceManager.GetString("Error_SuppliedDictionaryTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template directive must have non-empty name..
        /// </summary>
        internal static string Error_TemplateDirectiveCannotBeEmpty {
            get {
                return ResourceManager.GetString("Error_TemplateDirectiveCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must have a parameterless constructor..
        /// </summary>
        internal static string Error_TypeMustHaveParameterlessConstructor {
            get {
                return ResourceManager.GetString("Error_TypeMustHaveParameterlessConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} starting on line {0} was never closed..
        /// </summary>
        internal static string Error_UnclosedElement {
            get {
                return ResourceManager.GetString("Error_UnclosedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to undefined parameter entity &apos;{0}&apos;..
        /// </summary>
        internal static string Error_UndefinedParameterEntityReference {
            get {
                return ResourceManager.GetString("Error_UndefinedParameterEntityReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character &apos;{0}&apos;..
        /// </summary>
        internal static string Error_UnexpectedCharacter {
            get {
                return ResourceManager.GetString("Error_UnexpectedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected EOF parsing start tag &apos;{0}&apos;..
        /// </summary>
        internal static string Error_UnexpectedEndOfFileParsingStartTag {
            get {
                return ResourceManager.GetString("Error_UnexpectedEndOfFileParsingStartTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unresolvable entity &apos;{0}&apos;..
        /// </summary>
        internal static string Error_UnresolvableSgmlEntity {
            get {
                return ResourceManager.GetString("Error_UnresolvableSgmlEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type on the element rule, returned by &apos;{0}&apos; parameter, is not supported..
        /// </summary>
        internal static string Error_UnsupportedElementRule {
            get {
                return ResourceManager.GetString("Error_UnsupportedElementRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External parameter entity resolution..
        /// </summary>
        internal static string Error_UnsupportedExternalParameterEntityResolution {
            get {
                return ResourceManager.GetString("Error_UnsupportedExternalParameterEntityResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated string constant..
        /// </summary>
        internal static string Error_UnterminatedStringConstant {
            get {
                return ResourceManager.GetString("Error_UnterminatedStringConstant", resourceCulture);
            }
        }
    }
}
